# These are supported funding model platforms:

BTC (Silent Payment) Address:
sp1qqdak9clmvgxtrvcf36uwr93gddwwsyt734tsyemtf4xseeatxjuuwqm95sd7cctpt4ratnyg48c3n05ug5d5zfewlhf5kkaqzwkapn9wds8uh2w6

Monero (XMR) Address: 87h4wgQuVe4NMhxYMdUXmABCLhxEtRvzS8geVJw41YAvXx69S9PsJU2ffagVnw6tnbAX18v52Xai2GbZnqeEJw4UGs66E6K

Litecoin (LTC MWEB) Address:
ltcmweb1qqwxymvlgxyy5n5gtk6x0rzzhx0j80dcvjw9g9p8fv40cj2gv0d9w5qsc6209qz6uepyy5tjlm3935zst7z8h0cgtrsll2cv5959vphtssg6wrc3z
